### ISSUE TITLE
Cannot import Extreme_English_Proficiency

### ISSUE THREAD

**Issue by ahaw** [ggodlewski/smux-anki-converter#6]
While unpacking there is an exception:
42126   Listen and complete     null
99      About   null
Exception in thread "main" java.lang.NullPointerException
        at com.gitgis.sm.ItemConverter.parse(ItemConverter.java:92)
        at com.gitgis.sm.ItemConverter.getExercise(ItemConverter.java:52)
        at com.gitgis.sm.App.main(App.java:100)
On both 1.4 and 1.7 version.

**Comment by evgenybf** [comment]
smux-anki-converter 1.8 snapshot

The same problem with "EE Proficiency" deck dated September 2009. There is also a notable thing during parsing: a lot of generated files and directories have names "shifted" 1 position right
stemplate00008
template00002
litem00040.xm
litem00088.xm:

I've reproduced this error with a newer deck (2012) as well

**Comment by evgenybf** [comment]
Found a similar discussion where this issue left unresolved:
http://markmail.org/message/dv73bduccaj564xs#query:+page:1+mid:kwghjks6dsbjpoz7+state:results

**Comment by evgenybf** [comment]
A short debug has helped: the proficiency deck has been successfully parsed after adding +1 to this line:
SmPakParser.java, LIne 231
`int currentNamePos = this.namePos + readInt()  >>> + 1; <<<`

Although It breaks entry names in the decks which were correctly parsed before.
