### ISSUE TITLE
java.io.IOException: Negative seek offset

### ISSUE THREAD

**Issue by ardabro** [ggodlewski/smux-anki-converter#9]
Course: "English no problem 2"
After a long processing, with millions of mysterious numbers logged onto the screen,
after number "51617569" I got:

java.io.IOException: Negative seek offset
    at java.io.RandomAccessFile.seek(Native Method)
    at com.gitgis.sm.smpak.SmPakParser.scanEntrChnk(SmPakParser.java:203)
    at com.gitgis.sm.smpak.SmPakParser.open(SmPakParser.java:77)
    at com.gitgis.sm.smpak.SmPakParser.<init>(SmPakParser.java:27)
    at com.gitgis.sm.smpak.SmPakParser.getInstance(SmPakParser.java:32)
    at com.gitgis.sm.smpak.SmParser.<init>(SmParser.java:30)
    at com.gitgis.sm.App.main(App.java:55)
java.io.IOException: Negative seek offset
    at java.io.RandomAccessFile.seek(Native Method)
    at com.gitgis.sm.smpak.SmPakParser.scanEntrChnk(SmPakParser.java:203)
    at com.gitgis.sm.smpak.SmPakParser.getFileEntryNames(SmPakParser.java:350)
    at com.gitgis.sm.smpak.SmParser.getFileEntryNames(SmParser.java:55)
    at com.gitgis.sm.App.main(App.java:60)

**Comment by palkakrzysiek** [comment]
I think, it is because all the "no problem" courses had been recently updated and converter cannot handle it (yet). Remove *.smdif file from the course folder and try again.
